# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  bags:
    image: bags:latest
    ports:
      - 80:80
      - 443:443
    restart: always
